[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.2",
    "fastapi[standard]>=0.118.0",
    "httpx>=0.27.0",
    "openai>=2.1.0",
    "websocket-client>=1.8.0",
]
